/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trizno12;

import java.awt.event.KeyEvent;

/**
 *
 * @author Trizno
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        hapus ();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbilkedua = new javax.swing.JTextField();
        txtbilpertama = new javax.swing.JTextField();
        txthasil = new javax.swing.JTextField();
        plus = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        modulus = new javax.swing.JButton();
        akar = new javax.swing.JButton();
        kuadrat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bilangan Pertama :");

        jLabel2.setText("Bilangan Kedua :");

        jLabel3.setText("Hasil Bilangan :");

        txtbilkedua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbilkeduaActionPerformed(evt);
            }
        });
        txtbilkedua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbilkeduaKeyPressed(evt);
            }
        });

        txtbilpertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbilpertamaActionPerformed(evt);
            }
        });
        txtbilpertama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbilpertamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbilpertamaKeyTyped(evt);
            }
        });

        txthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasilActionPerformed(evt);
            }
        });

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });

        hapus.setText("Clear");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jLabel4.setText("Ini Kalkulator ");

        modulus.setText("%");
        modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusActionPerformed(evt);
            }
        });

        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });

        kuadrat.setText("x^2");
        kuadrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuadratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtbilpertama, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(txtbilkedua)
                    .addComponent(txthasil))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plus, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(akar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kali, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kuadrat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modulus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbilpertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus)
                    .addComponent(kali)
                    .addComponent(modulus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbilkedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(kuadrat)
                    .addComponent(minus)
                    .addComponent(bagi))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akar)
                    .addComponent(hapus))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbilkeduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbilkeduaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtbilkeduaActionPerformed

    private void txtbilpertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbilpertamaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtbilpertamaActionPerformed

    private void txthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasilActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        int bil = Integer.parseInt(txtbilpertama.getText());
        int bi2 = Integer.parseInt(txtbilkedua.getText());
        pengurangan(bil, bi2);
    }//GEN-LAST:event_minusActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        Double bil = Double.parseDouble(txtbilpertama.getText());
        Double bi2 = Double.parseDouble(txtbilkedua.getText());
        penjumlahan(bil, bi2);
    }//GEN-LAST:event_plusActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        int bil = Integer.parseInt(txtbilpertama.getText());
        int bi2 = Integer.parseInt(txtbilkedua.getText());
        perkalian(bil, bi2);
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        int bil = Integer.parseInt(txtbilpertama.getText());
        int bi2 = Integer.parseInt(txtbilkedua.getText());
        pembagian(bil, bi2);
    }//GEN-LAST:event_bagiActionPerformed

    private void modulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusActionPerformed
        // TODO add your handling code here:
        int bil = Integer.parseInt(txtbilpertama.getText());
        int bi2 = Integer.parseInt(txtbilkedua.getText());
        modulus(bil, bi2);
    }//GEN-LAST:event_modulusActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        txtbilpertama.setText("");
        txtbilkedua.setText("");
        txthasil.setText("");
        bagi.setEnabled(false);
        plus.setEnabled(false);
        minus.setEnabled(false);
        modulus.setEnabled(false);
        kali.setEnabled(false);
        akar.setEnabled(false);
        kuadrat.setEnabled(false);
       
    }//GEN-LAST:event_hapusActionPerformed

    private void txtbilkeduaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbilkeduaKeyPressed
        // TODO add your handling code here:
        minus.setEnabled(true);
        plus.setEnabled(true);
        kali.setEnabled(true);
        bagi.setEnabled(true);
        modulus.setEnabled(true);
        akar.setEnabled(true);
        kuadrat.setEnabled(true);
        
    }//GEN-LAST:event_txtbilkeduaKeyPressed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
        // TODO add your handling code here:
         int bi1 = Integer.parseInt(txtbilpertama.getText());
         akar(bi1);
    }//GEN-LAST:event_akarActionPerformed

    private void kuadratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuadratActionPerformed
        // TODO add your handling code here:
        int bil = Integer.parseInt(txtbilpertama.getText());
        int bi2 = Integer.parseInt(txtbilkedua.getText());
        kuadrat(bil, bi2);
    }//GEN-LAST:event_kuadratActionPerformed

    private void txtbilpertamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbilpertamaKeyPressed
        // TODO add your handling code here:
        akar.setEnabled(true);
    }//GEN-LAST:event_txtbilpertamaKeyPressed

    private void txtbilpertamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbilpertamaKeyTyped
//        // TODO add your handling code here:
//        char c = evt.getKeyChar();
//        if (! ((Character.isDigit(c) ||
//                (c == KeyEvent.VK_BACK_SPACE) ||
//                (c == KeyEvent.VK_DELETE))
//                )
//            )
//        {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtbilpertamaKeyTyped
        
    public void kuadrat(int bilangan1, int bilangan2) {
        double hasil = 0;
        hasil = Math.pow(bilangan1, bilangan2);
        txthasil.setText(hasil+"");
        
    }

    public void akar(int bilangan1) {
        double hasil = 0;
        hasil = Math.sqrt(bilangan1);
        txthasil.setText(hasil+"");
        
    }
    public void penjumlahan(Double bilangan1, Double bilangan2) {
        double hasil = 0;
        hasil = bilangan1 + bilangan2;
        txthasil.setText(hasil+"");
        
    }
    public void pengurangan(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 - bilangan2;
        txthasil.setText(hasil+"");
        
    }
    public void perkalian(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 * bilangan2;
        txthasil.setText(hasil+"");
        
    }
    public void pembagian(int bilangan1, int bilangan2) {
        float hasil = 0;
        hasil = bilangan1 / bilangan2;
        txthasil.setText(hasil+"");
        
    }
    public void modulus(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 % bilangan2;
        txthasil.setText(hasil+"");
        
    }
    
  public void hapus () {
        txthasil.setEnabled(false);
        txtbilpertama.setText("");
        txtbilkedua.setText("");
        txthasil.setText("");
        bagi.setEnabled(false);
        plus.setEnabled(false);
        minus.setEnabled(false);
        modulus.setEnabled(false);
        kali.setEnabled(false);
        akar.setEnabled(false);
        kuadrat.setEnabled(false);
        
  }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akar;
    private javax.swing.JButton bagi;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kali;
    private javax.swing.JButton kuadrat;
    private javax.swing.JButton minus;
    private javax.swing.JButton modulus;
    private javax.swing.JButton plus;
    private javax.swing.JTextField txtbilkedua;
    private javax.swing.JTextField txtbilpertama;
    private javax.swing.JTextField txthasil;
    // End of variables declaration//GEN-END:variables
}
